### ISSUE TITLE
Build as a library for embedding

### ISSUE THREAD

**Issue by PerryWerneck** [Tomas-M/iotop#10]
This is a suggestion: Is it possible to change iotop to work as a C/C++ library? This would allow developer to add this feature on other aplications, like monitoring systems.

**Comment by bbonev** [comment]
Check this out: https://github.com/HarryWei/iotop - HarryWei already did something like that. It is based on old code and may need some work. I see no problem integrating a change like this, I see these key points:

1) Clearly defined API
- opaque data structures with accessor functions
- versioned ABI
- external event loop for advanced apps
- internal event loop for simple apps

2) C library, usable from C++; maybe a C++ wrapper class

3) iotop itself should use the library itself

Do you have the ability and time to work on this?

I will help but can not do it all, because I have a list of things to add/change to the interface and those come first :)

**Comment by PerryWerneck** [comment]
Hi,

Yes. I have the ability and it's not the first time I do something like this; time it's another issue but I just cloned the Harry Wei project to my home project with the name libiotop and will starting working on it asap.

My first step will be build it as a library, after that, we can start to plan a clean api.

Thanks!

**Comment by bbonev** [comment]
Maybe it will be a better idea to make 3 way diff between current iotop codebase, Harry Wei's work and the common origin from where he forked. I have fixed a lot of things after he forked it.

In other words, most easy way will be to manually apply his work over the current code...

**Comment by PerryWerneck** [comment]
> Maybe it will be a better idea to make 3 way diff between current iotop codebase, Harry Wei's work and the common origin from where he forked. I have fixed a lot of things after he forked it.
> 
> In other words, most easy way will be to manually apply his work over the current code...

Ok! I forked and noticed that the code is failing; will redo it.

**Comment by PerryWerneck** [comment]
Working directly from your source in https://github.com/PerryWerneck/libioto.

- Added quick & dirt autoconf support for the library (it's easy for me, and for automated packaging)
- Starting to implement opaque structures (it'll take some time to finish).

**Comment by bbonev** [comment]
I see no benefit from autoconf in this case - the project is Linux only, ancient systems are not supported anyways, and cannot be supported because of missing kernel API, and besides moving the version define from a c header to the autoconf template it does not add any value - there is just nothing to configure here... For other projects autoconf definitely does many helpful things and adds value, but I believe this is not the case for iotop.

I saw that you planned moving the config part in the library - maybe its place is not there at all - a consumer app will have this and filter data by itself or by the help of the library for more complex cases.

As a hint, you can move only arr/checks/ioprio/uitls/vmstat/xxxid_info to the lib, the rest of the files are user interface related (curses or plain text), option parsing and configuration for the user interface - I think these have no place in the library. Maybe some refactoring of the internal data is a good idea - the data fetch operation is a relatively heavy one and applying filters there is not a good idea, so keeping all raw data in memory and refreshing it on certain interval is good for the lib, while leaving the filtering and configuration to the consumer... I have recently changed it to fetch both full and partial command lines, so pressing 'c' immediately changes and refreshes the view without re-fetching the data. Maybe there still are some leftovers of filtering based on config in xxxid_info, these should be moved to the interface.

About versioning and public API - this part is somewhat hectic - because there are many source files, `static` cannot be used to hide internal API functions. I will do that part after the lib reaches a finished/half-finished state. Doing that earlier is a loss of time :)

 Let me know when you think that my input is needed - I would like to propose a model where all changes are made in a separate repo and merged into the main one after it reaches ready to release state.

**Comment by PerryWerneck** [comment]
As a library one have to take care of a few control files (for pkgconfig, soname, etc) and autoconf helps to keep all the information in sync; it
helps to detect and adjust some distribution specifics for automated builds; it can be removed if proves unecessary.

Yes; I moving almost everithing to library for now; will be adjusting step by step as far I'm going more undertanting.

I saw that you planned moving the config part in the library - maybe its place is not there at all - a consumer app will have this and filter data by itself or by the help of the library for more complex cases.

The hing helps a lot!!

About versioning: This is one thing that autoconf helps; it keeps the version info in one place. 

To hide the internal APIs I already set macros IOTOP_API and  IOTOP_PRIVATE to set the correct visibility attribute; when finished only the IOTOP_API tagged functions will be exported.

About versioning and public API - this part is somewhat hectic - because there are many source files, static cannot be used to hide internal API functions. I will do that part after the lib reaches a finished/half-finished state. Doing that earlier is a loss of time :)

Your hints will always help but I think it will take some time until I get someting really usable.

Yes! The separate repo/branch is a best way to do this. I already do this on other projects. I even use separate repositores (combined with autobuild) to distribute installation packages to some selected 
users for testing on diferent distros/versions.

**Comment by bbonev** [comment]
Agreed :)

Sorry for misleading you a little bit - my work repo with the latest changes is https://github.com/bbonev/iotop/, I should have let you know earlier. After finishing a feature there, I push the changes here and release it...

> but I think it will take some time until I get someting really usable.

No hurries, take your time and let me know when ready.

**Comment by PerryWerneck** [comment]
Hi,

Just for your information because of the long time without activity: I still here, but, I had a big increase of work in my day job, and, because of this I have to slow down the work. Will resume it as soon as possible.

**Comment by bbonev** [comment]
Good to know. Same here with being busy :) I am preparing to make a new release soon...

**Comment by bbonev** [comment]
Lots of time have passed, do you plan to make that?

**Comment by PerryWerneck** [comment]
Unfortunatelly I'm with a lot of work now and cant continue.
