### ISSUE TITLE
Use with screen will cause alignment problems, a poison for patients with obsessive-compulsive disorder

### ISSUE THREAD

**Issue by harvey-git** [Tomas-M/iotop#22]
Use with screen will cause alignment problems, a poison for patients with obsessive-compulsive disorder
this normal
![normal](https://user-images.githubusercontent.com/52305566/136015889-3f4fde01-2c2a-4cd3-963b-94edbb6266b0.png)
and with screen
![with-screen](https://user-images.githubusercontent.com/52305566/136015940-1322b30d-ef9e-4ed5-9004-76a64a03d409.png)
Anyway, thank the author for this good work。
the python version authorization for non-root operation is too troublesome

**Comment by bbonev** [comment]
Can you provide more information:

Version of iotop
Version of ncurses
Value of TERM
What terminal program is in the secreenshots

Also does that happen in ASCII mode?

I need to reproduce the problem in order to provide a fix

**Comment by harvey-git** [comment]
> For value of TERM I mean the result of the following command (in screen and without it)
> 
> echo $TERM
this without
![normal](https://user-images.githubusercontent.com/52305566/136645521-a89b0845-50fd-4cd1-9853-6ae878c59ef6.png)

and this with screen
![screenshot](https://user-images.githubusercontent.com/52305566/136645527-5bc1d5b6-e0ab-4f5c-9885-00ed94c57959.png)


"ASCII mode is a feature of iotop, toggled by shortcut u - this will redraw the screen by avoiding UTF characters"

After the operation, the result of misalignment is the same

**Comment by bbonev** [comment]
I also use gnome-terminal, same TERM values in screen and without screen. But I can not reproduce that. I suppose the unwanted behavior happens because your terminal mis-interpretes something (Unicode or a control sequence, not sure which one) - my suggestion is to update the system where you run the gnome-terminal (or try with a more recent system).

The u shortcut is not a command line option, after you start iotop, then you press u to activate/deactivate that mode (it is a toggle).

**Comment by bbonev** [comment]
I am closing this, because of lack of feedback and I couldn't reproduce it. In case more info can be provided, please reopen.
