### ISSUE TITLE
iotop clarification

### ISSUE THREAD

**Issue by AkshayPai99** [Tomas-M/iotop#24]
Hi there, while using iotop in kubernetes pods I am getting an error as below.
Traceback (most recent call last):
  File "/usr/sbin/iotop", line 17, in <module>
    main()
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 737, in main
    main_loop()
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 727, in <lambda>
    main_loop = lambda: run_iotop(options)
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 620, in run_iotop
    return curses.wrapper(run_iotop_window, options)
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3/dist-packages/iotop/ui.py", line 609, in run_iotop_window
    taskstats_connection = TaskStatsNetlink(options)
  File "/usr/lib/python3/dist-packages/iotop/data.py", line 151, in __init__
    self.family_id = controller.get_family_id('TASKSTATS')
  File "/usr/lib/python3/dist-packages/iotop/genetlink.py", line 76, in get_family_id
    m = GeNlMessage.recv(self.conn)
  File "/usr/lib/python3/dist-packages/iotop/genetlink.py", line 56, in recv
    msg = conn.recv()
  File "/usr/lib/python3/dist-packages/iotop/netlink.py", line 255, in recv
    raise err
OSError: Netlink error: No such file or directory (2)

I already found out a solution for this. That is using below two configurations in k8s manifests
privileged : true
hostNetwork: true
But in our requirements it mandates to not use hostNetwork: true. So I just wanted to know why iotop demands hostNetwork : true ? And if you know any other way to run iotop without errors without using hostNetwork : true please let me know.

Thank You

**Comment by bbonev** [comment]
Hello,

From the above messages it seems that you are using the Python version, which is maintained by @pabs3 for the Debian project. The latest codebase is here https://repo.or.cz/iotop.git

This repository is of the C language re-implementation of iotop, packaged in most distributions as iotop-c. It will be nice if you can repeat your test with iotop-c as well because the two projects are very close in what they do and maybe the problem is also pertinent for iotop-c.

From what I see above, I guess that `hostNetwork: true` somehow implies `cap_net_admin` and because the IO statistics are collected from the kernel by `netlink`, that is the relation between iotop and networking. I am not aware in detail about the docker/k8s security model and I do not know if there is a more fine-grained knob to turn to enable only this functionality.

**Comment by pabs3** [comment]
Indeed, that crash is in the Python version of iotop. In commit 0881c06027b49c3e53fcfe803ba63e11b2090ef3 of the Python version of iotop, the error message was improved to include more details, here is what it says now:

```
The Linux kernel interfaces that iotop relies on for process I/O statistics
were not found. Please enable CONFIG_TASKSTATS in your Linux kernel build
configuration, use iotop outside a container and or share the host's
network namespace with the container.

Please do not file bugs on iotop about this.
```

Until the Linux kernel I/O statistics feature offers an alternative to netlink that doesn't require CAP_NET_ADMIN, I don't think this is fixable in iotop-py at least. Probably the Linux kernel namespace feature needs to be extended to netlink and the taskstats stuff. I don't have the Linux kernel experience needed to add support for that in the Linux kernel. 

https://blog.outlyer.com/using-netlink-to-calculate-load-averages
https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg924689.html
https://bugzilla.redhat.com/show_bug.cgi?id=1290691
https://bugs.openvz.org/browse/OVZ-5655

**Comment by guysoft** [comment]
Hey,
Perhaps it might be a good idea to note the differences between the projects int he README page. I had to look that up too.

**Comment by bbonev** [comment]
It is mentioned in the last sentence in third paragraph. If you can propose a better wording or more text and/or formatting, I'd appreciate...
