### ISSUE TITLE
Black bar in graph IO column

### ISSUE THREAD

**Issue by paulmenzel** [Tomas-M/iotop#33]
Testing iotop – using commit c10e6577 (Update contributors) – there is a black bar in the rsync row, but the usage is shown as 0. What does that mean?

![iotop-cut](https://user-images.githubusercontent.com/9318792/156170482-0692e4b1-1b81-41d8-a1fa-77053972775e.png)

**Comment by bbonev** [comment]
Is this a black and white terminal?

The black area seen above is intended to be gray and indicates that the process have exited. Also the whole line is grayed but that may not work on a BW only terminal.

The data points in the pseudo graph from the time the process was running are displayed normally while the ones after exit are grayed out.

See below how it is intended to look like:

![image](https://user-images.githubusercontent.com/658788/156229094-e1d7aba5-60e8-4706-9a0a-c3997c4f58fb.png)

**Comment by paulmenzel** [comment]
Thank you for your quick reply. It’s gnome-terminal and I ssh into a server. On the server:

    $ echo $TERM
    xterm-256color

**Comment by paulmenzel** [comment]
No idea, if something is set up incorrectly on the server system.

**Comment by bbonev** [comment]
The server is OK. It is a terminal problem.

`iotop` uses `attron(A_DIM)` to present exited processes. I believe that to be a more compatible approach on a broader terminal variety than selecting a specific color.

With the dark themes `A_DIM` makes the default foreground color darker and because in a dark theme the foreground color is normally a light one it works well.
With the light themes `gnome-terminal` does the same but since the default foreground color is a dark one, making it even darker makes no sense because it is visually indistinguishable.

IMHO the implementation of `A_DIM` on the terminal side should depend on dark vs light theme - it is OK to darken the foreground color on a dark theme, while in the light ones it should lighten it instead. FWIW `gnome-terminal` can programmatically check if the theme is light or dark and behave accordingly.

I see two possible courses of action:

1) You can file a bug in `gnome-terminal` to get this behavior fixed
2) I can change iotop to use a specific color instead of `A_DIM` (see above why I prefer not to do that)

**Comment by bbonev** [comment]
Closing this, since there is nothing actionable not covered in #31. Please reopen in case there is something to add.
