### ISSUE TITLE
FR: Switch to next larger prefix sooner

### ISSUE THREAD

**Issue by Atemu** [Tomas-M/iotop#49]
Currently, when you have multiple MiB/s of writes, you will often see values like `8000.00 K/s` as it only switches to the `M` prefix in the 10s of MiB/s.

The original python iotop switches somewhere in the neighbourhood of 2048K which I personally find easier to interpret and more aesthetically pleasing.

**Comment by bbonev** [comment]
Thanks for the suggestion.

One way to implement this is to introduce some threshold in the range `[1 .. 10]` and change `10000` to `thr*base`, assuming that the `base` is also configurable from `[1000, 1024]`.

As you can see all values are displayed in SI units (1000 instead of 1024) unlike iotop-py. Maybe this is another thing to make configurable, since personal preferences may vary. Then to get the same as iotop-py: `base=1024`, `thr=2`.

I will not be able to look into that this year. The code is here: https://github.com/Tomas-M/iotop/blob/master/src/views.c#L217, maybe you can make a PR if you want to see it happen faster? ;)
